---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY').split('/')[-2] }}"
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ role_name }}"
