---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_no_log: "{{ lookup('env', 'MOLECULE_NO_LOG') }}"
  tasks:
    - name: Set async_dir for HOME env
      ansible.builtin.set_fact:
        ansible_async_dir: "{{ lookup('env', 'HOME') | default('/tmp', true) }}/.ansible_async/"
      when: true

    - name: Destroy molecule instance(s)
      ansible.builtin.include_role:
        name: molecule.docker
        tasks_from: destroy
