---
scenario:
  name: default

driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
