---
# Supported platforms:
#   - geerlingguy/docker-ubuntu2204-ansible:latest
#   - geerlingguy/docker-almalinux9-ansible:latest
#   - geerlingguy/docker-almalinux10-ansible:latest

scenario:
  name: default
  test_sequence:
    - create
    - converge
    - destroy

driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2204-ansible:latest}
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  options:
    role: nutterbotterz.ansible_role_app
    
verifier:
  name: ansible
