name: Lint

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - next
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint -c .github/workflows/etc/.ansible-lint
